name: Snap.

jobs:

  snap:
    name: Ubuntu
    runs-on: ubuntu-latest

    env:
      UPLOAD_ARTIFACT: "true"

    steps:
      - name: Clone.
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: First set up.
        run: |
          sudo iptables -P FORWARD ACCEPT
          sudo snap install --classic snapcraft
          sudo usermod -aG lxd $USER
          sudo snap run lxd init --auto
          sudo snap run lxd waitready

      - name: Free up some disk space.
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be

      - name: Telegram Desktop snap build.
        run: sg lxd -c 'snap run snapcraft --verbosity=debug'

      - name: Move artifact.
        if: env.UPLOAD_ARTIFACT == 'true'
        run: |
          artifact_name=$(echo telegram-desktop_*.snap)
          echo "ARTIFACT_NAME=$artifact_name" >> $GITHUB_ENV

          mkdir artifact
          mv $artifact_name artifact

      - uses: actions/upload-artifact@v4
        if: env.UPLOAD_ARTIFACT == 'true'
        name: Upload artifact.
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: artifact
